### ISSUE TITLE
Synchronization of Trello and simple-todo

### ISSUE THREAD

**Issue by Freshchris01** [ovk/brackets-simple-todo#17]
Hy, I successfully connected the to-do plugin for Brackets with my Trello account. But I can't get the syncronization of my to-do list I created in Brackets working. I tried to create different lists in Trello and categories with the to-do plugin. How do I get this syncronized? Am I missing something?
Greetings Christian

**Comment by ovk** [comment]
Hello @Freshchris01,

First of all, please make sure that you selected **Trello** as a *To-Do Items Storage* on the *General* tab of the Simple To-Do Settings. Otherwise, you will see to-do items from a text file, even though you configured settings on the Trello tab. You can switch between storages any time.

As for synchronization with Trello, it is pretty simple. Your to-do list from Brackets is stored in a single Trello list. Each category from Brackets is stored as Trello card inside this list, and each to-do item from the category is stored as a Trello checkitem inside checklist attached to the card.

For example, the following Trello List:
![list](https://cloud.githubusercontent.com/assets/693072/6496924/06b8e434-c2a7-11e4-9c79-d4ef6e1084df.png)

Will be represented in Brackets as a to-do list with two categories:
![bracketslist](https://cloud.githubusercontent.com/assets/693072/6496937/323a86f8-c2a7-11e4-9c71-6090d44b1865.png)

As you can see, first category has two to-do items. You can see them in Trello just by clicking on this card:
![card](https://cloud.githubusercontent.com/assets/693072/6496958/88777f9e-c2a7-11e4-90a6-f8de0f9bfaa8.png)

And that is how these items are presented in Brackets:
![bracketsitems](https://cloud.githubusercontent.com/assets/693072/6496999/1133e552-c2a8-11e4-9f46-8558e6c66d68.png)

All changes you make in the Brackets are immediately pushed to Trello, and if you make any changes in Trello, you can sync with them by clicking on the *Reload to-do items* icon in Brackets.

**Comment by Freshchris01** [comment]
Thanks for your fast response... I'm stupid, I forgot to set the storage from textfile to Trello -.-
Everything is working so far, thanks for this pluggin!
